stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.1-jdk-8-slim
      shellScript: mvn clean package
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
